#!/bin/sh

set -eu

# quiet=true

## bobs tools #################################################################
R="\e[0m"
BOB="( c-[//]-[//])"
C1="\e[32;1m"
C2="\e[92m"
C3="\e[95m"
R="\e[0m"

bob_init() {
    printf "${C1}%s${R}\n" "bob is cooking $BOB"
}
bob_end() {
    printf "${C1}%s${R}\n" "bob cooked $BOB"
}
bob_say() {
    printf "${C2}[bob]${R}: %s\n" "$1"
}
bob_cmd() {
    printf "${C3}%s${R}\n" "$1"
}
## script #####################################################################
bob_init

milk_mode=false
# bigBaaain_mode=true
bigBaaain_mode=false

BIN_VM="./mr.sheep"
BIN_WOOL="./wool"
# WOOL_IN="./examples/wool/hello.wool"
WOOL_IN="./examples/wool/parrot.wool"
# WOOL_IN="./examples/wool/t.wool"
WOOL_OUT="./out/test.baa"

MILK_SRC="./src/milk.py"
MILK_IN="./in/test.milk"
MILK_OUT="./out/test.wool"

BB_SRC="./src/bigBaaain.py"
BB_IN="./examples/bigBaaain/helloworld.bf"
BB_OUT="./out/test.wool"

OUT="out/"

[ -d $OUT ] || mkdir -p $OUT

if $milk_mode; then
    bob_say "genreating wool code..."
    bob_cmd "python $MILK_SRC $MILK_IN $MILK_OUT"
    python $MILK_SRC $MILK_IN $MILK_OUT

    bob_say "genreating wool code..."
    bob_cmd "cat $MILK_OUT"
    cat $MILK_OUT
elif $bigBaaain_mode; then
    bob_say "genreating wool code..."
    bob_cmd "python $BB_SRC $BB_IN $BB_OUT"
    python $BB_SRC $BB_IN $BB_OUT

    bob_say "compiling binary"
    bob_cmd "$BIN_WOOL $BB_OUT $WOOL_OUT"
    # $BIN_WOOL $WOOL_IN $WOOL_OUT > /dev/null
    $BIN_WOOL $BB_OUT $WOOL_OUT

    bob_say "checking the binary file"
    bob_cmd "xxd -g 1 $WOOL_OUT"
    xxd -g 1 $WOOL_OUT

    bob_say "exec..."
    bob_cmd "$BIN_VM $WOOL_OUT"
    $BIN_VM $WOOL_OUT \
        && bob_say "exit code: $?" \
        || bob_say "exit code: $?"
else
    # gcc -E src/mr.sheep.c -o out/mr.sheep.proc.c
    # gcc -E src/wool.c -o out/wool.proc.c
    bob_say "compiling compiler..."
    bob_cmd "gcc -o $BIN_WOOL ./src/wool.c"
    gcc -o $BIN_WOOL ./src/wool.c

    bob_say "compiling vm..."
    bob_cmd "gcc -o $BIN_VM ./src/mr.sheep.c"
    gcc -o $BIN_VM ./src/mr.sheep.c

    bob_say "compiling binary"
    bob_cmd "$BIN_WOOL $WOOL_IN $WOOL_OUT"
    # $BIN_WOOL $WOOL_IN $WOOL_OUT > /dev/null
    $BIN_WOOL $WOOL_IN $WOOL_OUT

    bob_say "checking the binary file"
    bob_cmd "xxd -g 1 $WOOL_OUT"
    xxd -g 1 $WOOL_OUT

    bob_say "exec..."
    bob_cmd "$BIN_VM $WOOL_OUT"
    $BIN_VM $WOOL_OUT \
        && bob_say "exit code: $?" \
        || bob_say "exit code: $?"
    # $BIN_VM $WOOL_OUT && echo "all cool" || echo "not cool"
fi

bob_end
